export const AUTORIZACIONES = {
  // USUARIOS
  CONSULTAR_USUARIOS: "PERMISO_CONSULTAR_USUARIOS",
  ELIMINAR_USUARIOS: "PERMISO_ELIMINAR_USUARIOS",
  EDITAR_USUARIOS: "PERMISO_EDITAR_USUARIOS",
  CREAR_USUARIOS: "PERMISO_CREAR_USUARIOS",

  CONTRASENA_USUARIOS: "PERMISO_CONTRASEÑA_USUARIOS",
  CAMBIAR_CONTRASENA: "PERMISO_CAMBIAR_CONTRASEÑA_USUARIOS",
  DESHABILITAR_USUARIOS: "PERMISO_DESHABILITAR_USUARIOS",
  HABILITAR_USUARIOS: "PERMISO_HABILITAR_USUARIOS",

  // GRUPOS
  CONSULTAR_GRUPOS: "PERMISO_CONSULTAR_GRUPOS",
  ELIMINAR_GRUPOS: "PERMISO_ELIMINAR_GRUPOS",
  EDITAR_GRUPOS: "PERMISO_EDITAR_GRUPOS",
  CREAR_GRUPOS: "PERMISO_CREAR_GRUPOS",

  // PERMISOS
  CONSULTAR_PERMISOS: "PERMISO_CONSULTAR_PERMISOS",
  ELIMINAR_PERMISOS: "PERMISO_ELIMINAR_PERMISOS",
  EDITAR_PERMISOS: "PERMISO_EDITAR_PERMISOS",
  CREAR_PERMISOS: "PERMISO_CREAR_PERMISOS",

  // MODULOS
  CONSULTAR_MODULOS: "PERMISO_CONSULTAR_MODULOS",
  ELIMINAR_MODULOS: "PERMISO_ELIMINAR_MODULOS",
  EDITAR_MODULOS: "PERMISO_EDITAR_MODULOS",
  CREAR_MODULOS: "PERMISO_CREAR_MODULOS",
  DESHABILITAR_MODULOS: "PERMISO_DESHABILITAR_MODULOS",
  HABILITAR_MODULOS: "PERMISO_HABILITAR_MODULOS",

  // SUBMODULOS
  CONSULTAR_SUBMODULOS: "PERMISO_CONSULTAR_SUBMODULOS",
  ELIMINAR_SUBMODULOS: "PERMISO_ELIMINAR_SUBMODULOS",
  EDITAR_SUBMODULOS: "PERMISO_EDITAR_SUBMODULOS",
  CREAR_SUBMODULOS: "PERMISO_CREAR_SUBMODULOS",
  DESHABILITAR_SUBMODULOS: "PERMISO_DESHABILITAR_SUBMODULOS",
  HABILITAR_SUBMODULOS: "PERMISO_HABILITAR_SUBMODULOS",

  // ACCESOS
  SUBMODULO_CLIENTES: "SUBMODULO_CLIENTES_VENTAS",
  SUBMODULO_PRESUPUESTOS: "SUBMODULO_PRESUPUESTOS_VENTAS",
  SUBMODULO_PRODUCTOS: "SUBMODULO_PRODUCTOS_VENTAS",
} as const

export type Autorizacion = (typeof AUTORIZACIONES)[keyof typeof AUTORIZACIONES]
